# do not use "latest" here, if you want this to work in the future
image: docker:19

services:
  - docker:dind

stages:
  - build

before_script:
  - docker version
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest





# aws ecr get-login-password --region ap-southeast-1 | docker login --username hung_test_dev

# aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 440638714536.dkr.ecr.ap-southeast-1.amazonaws.com

# aws ecr get-login-password | docker login --username AWS --password-stdin 623866230960.dkr.ecr.ap-southeast-1.amazonaws.com

# aws ecr create-repository --repository-name test_ecs_ecr --region ap-southeast-1